export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "Artificial Intelligence"
  | "Machine Learning"
  | "Data Analysis"
  | "Quality Assurance"
  | "Leadership"
  | "Entrepreneurship"
  | "Product Strategy"
  | "AI Strategy"
  | "Full-stack Development"
  | "AI Model Deployment"
  | "Policy Development"
  | "Cross-cultural Communication"
  | "Process Improvement"
  | "Content Moderation"
  | "Policy Analysis"
  | "Multilingual Communication"
  | "Trend Analysis"
  | "Community Guidelines"
  | "Graphic Design"
  | "Administrative Support"
  | "Client Communication"
  | "Print Production"
  | "Creative Design"
  | "Community Building"
  | "Project Management"
  | "UI/UX Design"
  | "Cultural Exchange"
  | "International Relations"
  | "Archaeology"
  | "Business Strategy"
  | "Mentoring"
  | "Workshop Facilitation"
  | "Innovation Strategy"
  | "Lean Six Sigma";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "AI"
  | "Full-stack"
  | "Data Analysis"
  | "Quality Assurance"
  | "Community"
  | "Leadership"
  | "Social Impact"
  | "Design"
  | "Creative"
  | "Globalization"
  | "Education"
  | "Innovation"
  | "Entrepreneurship"
  | "Mentoring"
  | "Business"
  | "Quality"
  | "Process Improvement";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
