export const siteConfig = {
  name: "Nur Syazwani Naqibah | AI Strategist & Entrepreneur Portfolio",
  authorName: "Nur Syazwani Naqibah",
  username: "syazwaninaqibah",
  description:
    "Nur Syazwani Naqibah's portfolio - Entrepreneur and AI strategist building innovative digital solutions for the future of work. Founder of Employou Technologies, leveraging AI to revolutionize various industries.",
  url: "https://snaqibah.my",
  links: {
    linkedin: "https://linkedin.com/in/nur-syazwani-naqibah",
    website: "https://snaqibah.my",
  },
  ogImage: "https://snaqibah.my/profile-img.png",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Nur Syazwani Naqibah",
    "AI Strategist",
    "AI Entrepreneur Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "AI strategist portfolio",
    "Entrepreneur portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
